# Usa una imagen base de Python
FROM python:3.9-slim

# Crea un directorio para la app
WORKDIR /app

# Copia los archivos de la aplicación
COPY src/ /app

# Copia el archivo de requisitos
COPY requirements.txt /app

# Instala venv y crea el entorno virtual
RUN python -m venv venv

# Activa el entorno virtual e instala las dependencias
RUN . venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt

# Expone el puerto 8080
EXPOSE 8080

# Cambia a un usuario no root
RUN useradd -m myuser
USER myuser

# Define el comando de ejecución
CMD ["venv/bin/python", "app.py"]
